### ISSUE TITLE
Custom cobrapy/optlang dependency

### ISSUE THREAD

**Issue by braceal** [kbaseapps/COBRApyBasedFBA#1]
We need to add the forked versions of cobrapy and optlang that contain the COINOR-CBC and OSQP solvers.

This was the way that I installed them for testing. We can probably run the installs for optlang and cobrapy without the -e flag.
@Fxe what is the best way to add this to the docker image?

```
git clone https://github.com/braceal/MFApy.git
cd MFApy
python3 -m venv env
source env/bin/activate
pip install --upgrade pip setuptools wheel
mkdir deps && cd deps
git clone https://github.com/braceal/optlang.git
cd optlang && git checkout test/coinor-cbc_osqp && cd ..
git clone https://github.com/braceal/cobrapy.git
cd cobrapy && git ceckout feature/coinor-cbc_osqp && cd ..
pip install -e optlang/
pip install -e cobrapy/
cd .. && pip install -e .
```

**Comment by Fxe** [comment]
you can add that do the docker
here I have 2 python libs not in pypi in this example https://github.com/Fxe/modelseed-annotation-server/blob/master/Dockerfile
make sure that "custom" cobrapy version is 0.17.1 or above otherwise cobrakbase will update it from pypi

What is MFApy for?

**Comment by braceal** [comment]
Great! I will take a look. MFApy was just the name of the package I made for testing (a precursor to this package).
